---
- hosts: centos
  become: true
  vars:
    description: "{{ ansible_hostname }}"
  tasks:
    - name: write the index file
      template: src=template.j2 dest=/var/www/html/index.html
      notify:
        # permet de redemarrer appache (lancement handlers restart httpd si copy faite
        - restart httpd
    - name: ensure apache is running
      service:  name=httpd state=started

  handlers:
    - name: restart httpd
      service: name=httpd state=restarted


  
